version: '3.4'

services:
  messageservice:
    image: ${DOCKER_REGISTRY-}messageservice
    build:
      context: .
      dockerfile: Services/MessageService/Dockerfile

  listenerservice:
    image: ${DOCKER_REGISTRY-}listenerservice
    build:
      context: .
      dockerfile: Services/ListenerService/Dockerfile


